namespace Notifications.Domain.Enums
{
    public enum NotificationTypeTagEnum
    {
        SUPPLIERS_PORTAL_ACTIVATE_ACCOUNT,
        SUPPLIERS_PORTAL_UNKNOWN_UNIT_OF_MEASURE,
        SUPPLIERS_PORTAL_ORDER_CLIENT_CANCELED,
        SUPPLIERS_PORTAL_ORDER_SUPPLIER_CANCELED,
        SUPPLIERS_PORTAL_ORDER_CANCELED,
        SUPPLIERS_PORTAL_ORDER_UNPROCESSED,
        SUPPLIERS_PORTAL_ORDER_IN_TRANSIT,
        SUPPLIERS_PORTAL_ORDER_DELAYED,
        SUPPLIERS_PORTAL_ORDER_CANCELED_DANGER,
        SUPPLIERS_PORTAL_ORDER_UNPROCESSED_DANGER,
        PAVAL_HOLDING_NOTIFY_ABOUT_REQUEST
    }
}